services:
    mukadi_settings.setting:
        class: Mukadi\SettingsBundle\Model\Setting
        arguments:
            - @form.factory
            - @mukadi_settings.data_manager
            - %mukadi_settings_param_class%
            - %mukadi_settings_settings%