services:
    mukadi_settings.type.text:
        class: Mukadi\SettingsBundle\Types\TextType
        public: false
        tags:
            - { name: mukadi_settings.setting_type, alias: text }
    mukadi_settings.type.toggle:
        class: Mukadi\SettingsBundle\Types\ToggleType
        public: false
        tags:
            - { name: mukadi_settings.setting_type, alias: toggle }
    mukadi_settings.type.email:
        class: Mukadi\SettingsBundle\Types\EmailType
        public: false
        tags:
            - { name: mukadi_settings.setting_type, alias: email }
    mukadi_settings.type.datetime:
        class: Mukadi\SettingsBundle\Types\DateTimeType
        public: false
        tags:
            - { name: mukadi_settings.setting_type, alias: datetime }
    mukadi_settings.type.date:
        class: Mukadi\SettingsBundle\Types\DateType
        public: false
        tags:
            - { name: mukadi_settings.setting_type, alias: date }
    mukadi_settings.type.choice:
        class: Mukadi\SettingsBundle\Types\ChoiceType
        public: false
        tags:
            - { name: mukadi_settings.setting_type, alias: choice }
    mukadi_settings.type.textarea:
        class: Mukadi\SettingsBundle\Types\TextareaType
        public: false
        tags:
            - { name: mukadi_settings.setting_type, alias: textarea }
    mukadi_settings.type.integer:
        class: Mukadi\SettingsBundle\Types\IntegerType
        public: false
        tags:
            - { name: mukadi_settings.setting_type, alias: integer }
    mukadi_settings.type.number:
        class: Mukadi\SettingsBundle\Types\NumberType
        public: false
        tags:
            - { name: mukadi_settings.setting_type, alias: number }
    mukadi_settings.type.entity:
        class: Mukadi\SettingsBundle\Types\EntityType
        public: false
        arguments: ["@mukadi_settings.data_manager"]
        tags:
            - { name: mukadi_settings.setting_type, alias: entity }